In [2]:
import numpy as np

In [4]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [6]:
np.array(test_matrix).reshape(4,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [8]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [10]:
#reshape

In [12]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [13]:
np.array(test_matrix).reshape(1,-1).shape

(1, 8)

In [15]:
np.array(test_matrix).reshape(1,-1,2).shape

(1, 4, 2)

In [17]:
#flatten

In [19]:
test_matrix = [[1,2,3,4],[1,2,5,8],[1,2,3,4],[1,2,5,8]]

In [22]:
np.array(test_matrix)

array([[1, 2, 3, 4],
       [1, 2, 5, 8],
       [1, 2, 3, 4],
       [1, 2, 5, 8]])

In [28]:
test_matrix

array([[1, 2, 3, 4],
       [1, 2, 5, 8],
       [1, 2, 3, 4],
       [1, 2, 5, 8]])

In [30]:
test_matrix = np.array(test_matrix)
test_matrix.shape

(4, 4)

In [32]:
np.array(test_matrix).flatten().shape

(16,)

In [34]:
print(test_matrix)

[[1 2 3 4]
 [1 2 5 8]
 [1 2 3 4]
 [1 2 5 8]]


In [37]:
print(np.array(test_matrix).flatten())

[1 2 3 4 1 2 5 8 1 2 3 4 1 2 5 8]
