In [2]:
import numpy as np

In [4]:
list(range(0,10,3))

[0, 3, 6, 9]

In [7]:
type(list(range(30)))

list

In [8]:
# range: list 의 range와 같은 효과,
# integer로 0부터 29까지 배열 추출
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [12]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [14]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [16]:
#ones zeros& empty

In [18]:
np.zeros(shape=(10,),dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [20]:
np.zeros(shape=(2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(shape=(10,))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
np.empty(shape=(10,),dtype=np.int8)

array([115,  32, 116, 104, 101,  32, 115, 101, 114, 105], dtype=int8)

In [54]:
np.empty((10,5))

array([[1.09821493e-311, 1.09821298e-311, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [9.85330622e+165, 3.47572992e-143, 6.19941898e-071,
        6.20012019e+179, 9.16281386e-072],
       [5.20875727e+045, 6.72775436e+199, 1.42137845e-076,
        1.22448153e+218, 9.45956265e-076],
       [9.16281387e-072, 1.74226842e-152, 4.35294652e-114,
        5.04499704e+223, 2.11418369e+257],
       [1.69724950e+137, 1.61410559e+132, 6.01390868e-154,
        6.01347002e-154, 6.01347002e-154],
       [2.95160906e-075, 4.11017660e+223, 6.19941898e-071,
        6.98191945e+252, 2.14392305e+137],
       [9.02193423e+217, 6.19941898e-071, 2.95153379e-075,
        1.54152961e+256, 5.28758935e+180],
       [1.68818134e+195, 1.28515803e+248, 5.45593133e-095,
        5.49109388e-143, 2.87249161e+161],
       [4.31814724e-096, 5.55603593e+180, 9.05770475e+271,
        9.90846063e+024, 3.68421875e+180],
       [1.69375695e+190, 2.17733445e-076, 1.90549508e-094,
        2.84859970e-110

In [56]:
test_matrix=np.arange(100).reshape(5,-1)
test_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [58]:
test_matrix.shape

(5, 20)

In [62]:
np.zeros_like(test_matrix, dtype=np.float32)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [64]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [65]:
np.identity(n=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [67]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
matrix=np.arange(9).reshape(3,3)
print(matrix)
print("대각 행렬 추출값")
np.diag(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
대각 행렬 추출값


array([0, 4, 8])

In [72]:
np.diag(matrix,k=1)

array([1, 5])

In [74]:
np.diag(matrix,k=-1)

array([3, 7])

In [76]:
np.random.normal(0,1,10).reshape(2,5)

array([[ 1.14646968,  0.8399673 ,  0.42378361, -0.62748451, -1.18359638],
       [-0.7968957 , -0.97685622,  0.25271454,  0.80303245,  1.68706613]])

In [81]:
np.random.exponential(scale=2, size=100)

array([6.77096049, 1.24266511, 0.20745824, 0.73656855, 0.09761238,
       4.18559528, 3.76821786, 0.3180325 , 2.63146269, 2.6949141 ,
       5.07099441, 0.85887408, 0.02251888, 0.06730481, 0.39677473,
       0.40468076, 7.30344752, 0.17587577, 0.31362521, 1.35565112,
       1.36458731, 4.65196015, 0.86891483, 3.34507062, 1.00199993,
       0.47383936, 7.42180824, 1.49664131, 2.72472782, 3.11560195,
       0.29748381, 0.8104343 , 0.72205668, 3.21831895, 2.10585165,
       1.68054711, 1.5013363 , 3.85303123, 2.65760969, 0.37417726,
       0.50743161, 1.70320301, 0.08282753, 0.26743147, 3.35379327,
       4.79469433, 0.06596754, 0.99002113, 2.28990097, 4.96963027,
       0.35460013, 1.11828473, 0.52111046, 1.62764622, 1.3606961 ,
       1.54832783, 0.12787033, 0.95331711, 1.02271294, 2.41345117,
       2.16676584, 2.88460228, 0.82407822, 1.39913257, 1.73540262,
       4.47717657, 0.90532755, 0.28304663, 1.37988364, 0.10106831,
       6.66578035, 0.03958232, 5.34464503, 2.86439517, 0.18829